# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gwagdong-u/irc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gwagdong-u/irc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gwagdong-u/irc/CMakeFiles /Users/gwagdong-u/irc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gwagdong-u/irc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ft_irc

# Build rule for target.
ft_irc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ft_irc
.PHONY : ft_irc

# fast build rule for target.
ft_irc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/build
.PHONY : ft_irc/fast

src/commands/CommandHandler.o: src/commands/CommandHandler.cpp.o
.PHONY : src/commands/CommandHandler.o

# target to build an object file
src/commands/CommandHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/CommandHandler.cpp.o
.PHONY : src/commands/CommandHandler.cpp.o

src/commands/CommandHandler.i: src/commands/CommandHandler.cpp.i
.PHONY : src/commands/CommandHandler.i

# target to preprocess a source file
src/commands/CommandHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/CommandHandler.cpp.i
.PHONY : src/commands/CommandHandler.cpp.i

src/commands/CommandHandler.s: src/commands/CommandHandler.cpp.s
.PHONY : src/commands/CommandHandler.s

# target to generate assembly for a file
src/commands/CommandHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/CommandHandler.cpp.s
.PHONY : src/commands/CommandHandler.cpp.s

src/commands/impl/InviteCommand.o: src/commands/impl/InviteCommand.cpp.o
.PHONY : src/commands/impl/InviteCommand.o

# target to build an object file
src/commands/impl/InviteCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/InviteCommand.cpp.o
.PHONY : src/commands/impl/InviteCommand.cpp.o

src/commands/impl/InviteCommand.i: src/commands/impl/InviteCommand.cpp.i
.PHONY : src/commands/impl/InviteCommand.i

# target to preprocess a source file
src/commands/impl/InviteCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/InviteCommand.cpp.i
.PHONY : src/commands/impl/InviteCommand.cpp.i

src/commands/impl/InviteCommand.s: src/commands/impl/InviteCommand.cpp.s
.PHONY : src/commands/impl/InviteCommand.s

# target to generate assembly for a file
src/commands/impl/InviteCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/InviteCommand.cpp.s
.PHONY : src/commands/impl/InviteCommand.cpp.s

src/commands/impl/JoinCommand.o: src/commands/impl/JoinCommand.cpp.o
.PHONY : src/commands/impl/JoinCommand.o

# target to build an object file
src/commands/impl/JoinCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/JoinCommand.cpp.o
.PHONY : src/commands/impl/JoinCommand.cpp.o

src/commands/impl/JoinCommand.i: src/commands/impl/JoinCommand.cpp.i
.PHONY : src/commands/impl/JoinCommand.i

# target to preprocess a source file
src/commands/impl/JoinCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/JoinCommand.cpp.i
.PHONY : src/commands/impl/JoinCommand.cpp.i

src/commands/impl/JoinCommand.s: src/commands/impl/JoinCommand.cpp.s
.PHONY : src/commands/impl/JoinCommand.s

# target to generate assembly for a file
src/commands/impl/JoinCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/JoinCommand.cpp.s
.PHONY : src/commands/impl/JoinCommand.cpp.s

src/commands/impl/KickCommand.o: src/commands/impl/KickCommand.cpp.o
.PHONY : src/commands/impl/KickCommand.o

# target to build an object file
src/commands/impl/KickCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/KickCommand.cpp.o
.PHONY : src/commands/impl/KickCommand.cpp.o

src/commands/impl/KickCommand.i: src/commands/impl/KickCommand.cpp.i
.PHONY : src/commands/impl/KickCommand.i

# target to preprocess a source file
src/commands/impl/KickCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/KickCommand.cpp.i
.PHONY : src/commands/impl/KickCommand.cpp.i

src/commands/impl/KickCommand.s: src/commands/impl/KickCommand.cpp.s
.PHONY : src/commands/impl/KickCommand.s

# target to generate assembly for a file
src/commands/impl/KickCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/KickCommand.cpp.s
.PHONY : src/commands/impl/KickCommand.cpp.s

src/commands/impl/ModeCommand.o: src/commands/impl/ModeCommand.cpp.o
.PHONY : src/commands/impl/ModeCommand.o

# target to build an object file
src/commands/impl/ModeCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/ModeCommand.cpp.o
.PHONY : src/commands/impl/ModeCommand.cpp.o

src/commands/impl/ModeCommand.i: src/commands/impl/ModeCommand.cpp.i
.PHONY : src/commands/impl/ModeCommand.i

# target to preprocess a source file
src/commands/impl/ModeCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/ModeCommand.cpp.i
.PHONY : src/commands/impl/ModeCommand.cpp.i

src/commands/impl/ModeCommand.s: src/commands/impl/ModeCommand.cpp.s
.PHONY : src/commands/impl/ModeCommand.s

# target to generate assembly for a file
src/commands/impl/ModeCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/ModeCommand.cpp.s
.PHONY : src/commands/impl/ModeCommand.cpp.s

src/commands/impl/NickCommand.o: src/commands/impl/NickCommand.cpp.o
.PHONY : src/commands/impl/NickCommand.o

# target to build an object file
src/commands/impl/NickCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/NickCommand.cpp.o
.PHONY : src/commands/impl/NickCommand.cpp.o

src/commands/impl/NickCommand.i: src/commands/impl/NickCommand.cpp.i
.PHONY : src/commands/impl/NickCommand.i

# target to preprocess a source file
src/commands/impl/NickCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/NickCommand.cpp.i
.PHONY : src/commands/impl/NickCommand.cpp.i

src/commands/impl/NickCommand.s: src/commands/impl/NickCommand.cpp.s
.PHONY : src/commands/impl/NickCommand.s

# target to generate assembly for a file
src/commands/impl/NickCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/NickCommand.cpp.s
.PHONY : src/commands/impl/NickCommand.cpp.s

src/commands/impl/NoticeCommand.o: src/commands/impl/NoticeCommand.cpp.o
.PHONY : src/commands/impl/NoticeCommand.o

# target to build an object file
src/commands/impl/NoticeCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/NoticeCommand.cpp.o
.PHONY : src/commands/impl/NoticeCommand.cpp.o

src/commands/impl/NoticeCommand.i: src/commands/impl/NoticeCommand.cpp.i
.PHONY : src/commands/impl/NoticeCommand.i

# target to preprocess a source file
src/commands/impl/NoticeCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/NoticeCommand.cpp.i
.PHONY : src/commands/impl/NoticeCommand.cpp.i

src/commands/impl/NoticeCommand.s: src/commands/impl/NoticeCommand.cpp.s
.PHONY : src/commands/impl/NoticeCommand.s

# target to generate assembly for a file
src/commands/impl/NoticeCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/NoticeCommand.cpp.s
.PHONY : src/commands/impl/NoticeCommand.cpp.s

src/commands/impl/PartCommand.o: src/commands/impl/PartCommand.cpp.o
.PHONY : src/commands/impl/PartCommand.o

# target to build an object file
src/commands/impl/PartCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PartCommand.cpp.o
.PHONY : src/commands/impl/PartCommand.cpp.o

src/commands/impl/PartCommand.i: src/commands/impl/PartCommand.cpp.i
.PHONY : src/commands/impl/PartCommand.i

# target to preprocess a source file
src/commands/impl/PartCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PartCommand.cpp.i
.PHONY : src/commands/impl/PartCommand.cpp.i

src/commands/impl/PartCommand.s: src/commands/impl/PartCommand.cpp.s
.PHONY : src/commands/impl/PartCommand.s

# target to generate assembly for a file
src/commands/impl/PartCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PartCommand.cpp.s
.PHONY : src/commands/impl/PartCommand.cpp.s

src/commands/impl/PassCommand.o: src/commands/impl/PassCommand.cpp.o
.PHONY : src/commands/impl/PassCommand.o

# target to build an object file
src/commands/impl/PassCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PassCommand.cpp.o
.PHONY : src/commands/impl/PassCommand.cpp.o

src/commands/impl/PassCommand.i: src/commands/impl/PassCommand.cpp.i
.PHONY : src/commands/impl/PassCommand.i

# target to preprocess a source file
src/commands/impl/PassCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PassCommand.cpp.i
.PHONY : src/commands/impl/PassCommand.cpp.i

src/commands/impl/PassCommand.s: src/commands/impl/PassCommand.cpp.s
.PHONY : src/commands/impl/PassCommand.s

# target to generate assembly for a file
src/commands/impl/PassCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PassCommand.cpp.s
.PHONY : src/commands/impl/PassCommand.cpp.s

src/commands/impl/PingCommand.o: src/commands/impl/PingCommand.cpp.o
.PHONY : src/commands/impl/PingCommand.o

# target to build an object file
src/commands/impl/PingCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PingCommand.cpp.o
.PHONY : src/commands/impl/PingCommand.cpp.o

src/commands/impl/PingCommand.i: src/commands/impl/PingCommand.cpp.i
.PHONY : src/commands/impl/PingCommand.i

# target to preprocess a source file
src/commands/impl/PingCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PingCommand.cpp.i
.PHONY : src/commands/impl/PingCommand.cpp.i

src/commands/impl/PingCommand.s: src/commands/impl/PingCommand.cpp.s
.PHONY : src/commands/impl/PingCommand.s

# target to generate assembly for a file
src/commands/impl/PingCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PingCommand.cpp.s
.PHONY : src/commands/impl/PingCommand.cpp.s

src/commands/impl/PongCommand.o: src/commands/impl/PongCommand.cpp.o
.PHONY : src/commands/impl/PongCommand.o

# target to build an object file
src/commands/impl/PongCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PongCommand.cpp.o
.PHONY : src/commands/impl/PongCommand.cpp.o

src/commands/impl/PongCommand.i: src/commands/impl/PongCommand.cpp.i
.PHONY : src/commands/impl/PongCommand.i

# target to preprocess a source file
src/commands/impl/PongCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PongCommand.cpp.i
.PHONY : src/commands/impl/PongCommand.cpp.i

src/commands/impl/PongCommand.s: src/commands/impl/PongCommand.cpp.s
.PHONY : src/commands/impl/PongCommand.s

# target to generate assembly for a file
src/commands/impl/PongCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PongCommand.cpp.s
.PHONY : src/commands/impl/PongCommand.cpp.s

src/commands/impl/PrivMsgCommand.o: src/commands/impl/PrivMsgCommand.cpp.o
.PHONY : src/commands/impl/PrivMsgCommand.o

# target to build an object file
src/commands/impl/PrivMsgCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PrivMsgCommand.cpp.o
.PHONY : src/commands/impl/PrivMsgCommand.cpp.o

src/commands/impl/PrivMsgCommand.i: src/commands/impl/PrivMsgCommand.cpp.i
.PHONY : src/commands/impl/PrivMsgCommand.i

# target to preprocess a source file
src/commands/impl/PrivMsgCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PrivMsgCommand.cpp.i
.PHONY : src/commands/impl/PrivMsgCommand.cpp.i

src/commands/impl/PrivMsgCommand.s: src/commands/impl/PrivMsgCommand.cpp.s
.PHONY : src/commands/impl/PrivMsgCommand.s

# target to generate assembly for a file
src/commands/impl/PrivMsgCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/PrivMsgCommand.cpp.s
.PHONY : src/commands/impl/PrivMsgCommand.cpp.s

src/commands/impl/QuitCommand.o: src/commands/impl/QuitCommand.cpp.o
.PHONY : src/commands/impl/QuitCommand.o

# target to build an object file
src/commands/impl/QuitCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/QuitCommand.cpp.o
.PHONY : src/commands/impl/QuitCommand.cpp.o

src/commands/impl/QuitCommand.i: src/commands/impl/QuitCommand.cpp.i
.PHONY : src/commands/impl/QuitCommand.i

# target to preprocess a source file
src/commands/impl/QuitCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/QuitCommand.cpp.i
.PHONY : src/commands/impl/QuitCommand.cpp.i

src/commands/impl/QuitCommand.s: src/commands/impl/QuitCommand.cpp.s
.PHONY : src/commands/impl/QuitCommand.s

# target to generate assembly for a file
src/commands/impl/QuitCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/QuitCommand.cpp.s
.PHONY : src/commands/impl/QuitCommand.cpp.s

src/commands/impl/TopicCommand.o: src/commands/impl/TopicCommand.cpp.o
.PHONY : src/commands/impl/TopicCommand.o

# target to build an object file
src/commands/impl/TopicCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/TopicCommand.cpp.o
.PHONY : src/commands/impl/TopicCommand.cpp.o

src/commands/impl/TopicCommand.i: src/commands/impl/TopicCommand.cpp.i
.PHONY : src/commands/impl/TopicCommand.i

# target to preprocess a source file
src/commands/impl/TopicCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/TopicCommand.cpp.i
.PHONY : src/commands/impl/TopicCommand.cpp.i

src/commands/impl/TopicCommand.s: src/commands/impl/TopicCommand.cpp.s
.PHONY : src/commands/impl/TopicCommand.s

# target to generate assembly for a file
src/commands/impl/TopicCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/TopicCommand.cpp.s
.PHONY : src/commands/impl/TopicCommand.cpp.s

src/commands/impl/UserCommand.o: src/commands/impl/UserCommand.cpp.o
.PHONY : src/commands/impl/UserCommand.o

# target to build an object file
src/commands/impl/UserCommand.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/UserCommand.cpp.o
.PHONY : src/commands/impl/UserCommand.cpp.o

src/commands/impl/UserCommand.i: src/commands/impl/UserCommand.cpp.i
.PHONY : src/commands/impl/UserCommand.i

# target to preprocess a source file
src/commands/impl/UserCommand.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/UserCommand.cpp.i
.PHONY : src/commands/impl/UserCommand.cpp.i

src/commands/impl/UserCommand.s: src/commands/impl/UserCommand.cpp.s
.PHONY : src/commands/impl/UserCommand.s

# target to generate assembly for a file
src/commands/impl/UserCommand.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/commands/impl/UserCommand.cpp.s
.PHONY : src/commands/impl/UserCommand.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/network/Channel.o: src/network/Channel.cpp.o
.PHONY : src/network/Channel.o

# target to build an object file
src/network/Channel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/network/Channel.cpp.o
.PHONY : src/network/Channel.cpp.o

src/network/Channel.i: src/network/Channel.cpp.i
.PHONY : src/network/Channel.i

# target to preprocess a source file
src/network/Channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/network/Channel.cpp.i
.PHONY : src/network/Channel.cpp.i

src/network/Channel.s: src/network/Channel.cpp.s
.PHONY : src/network/Channel.s

# target to generate assembly for a file
src/network/Channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/network/Channel.cpp.s
.PHONY : src/network/Channel.cpp.s

src/network/Client.o: src/network/Client.cpp.o
.PHONY : src/network/Client.o

# target to build an object file
src/network/Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/network/Client.cpp.o
.PHONY : src/network/Client.cpp.o

src/network/Client.i: src/network/Client.cpp.i
.PHONY : src/network/Client.i

# target to preprocess a source file
src/network/Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/network/Client.cpp.i
.PHONY : src/network/Client.cpp.i

src/network/Client.s: src/network/Client.cpp.s
.PHONY : src/network/Client.s

# target to generate assembly for a file
src/network/Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/network/Client.cpp.s
.PHONY : src/network/Client.cpp.s

src/network/Server.o: src/network/Server.cpp.o
.PHONY : src/network/Server.o

# target to build an object file
src/network/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/network/Server.cpp.o
.PHONY : src/network/Server.cpp.o

src/network/Server.i: src/network/Server.cpp.i
.PHONY : src/network/Server.i

# target to preprocess a source file
src/network/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/network/Server.cpp.i
.PHONY : src/network/Server.cpp.i

src/network/Server.s: src/network/Server.cpp.s
.PHONY : src/network/Server.s

# target to generate assembly for a file
src/network/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ft_irc.dir/build.make CMakeFiles/ft_irc.dir/src/network/Server.cpp.s
.PHONY : src/network/Server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ft_irc"
	@echo "... src/commands/CommandHandler.o"
	@echo "... src/commands/CommandHandler.i"
	@echo "... src/commands/CommandHandler.s"
	@echo "... src/commands/impl/InviteCommand.o"
	@echo "... src/commands/impl/InviteCommand.i"
	@echo "... src/commands/impl/InviteCommand.s"
	@echo "... src/commands/impl/JoinCommand.o"
	@echo "... src/commands/impl/JoinCommand.i"
	@echo "... src/commands/impl/JoinCommand.s"
	@echo "... src/commands/impl/KickCommand.o"
	@echo "... src/commands/impl/KickCommand.i"
	@echo "... src/commands/impl/KickCommand.s"
	@echo "... src/commands/impl/ModeCommand.o"
	@echo "... src/commands/impl/ModeCommand.i"
	@echo "... src/commands/impl/ModeCommand.s"
	@echo "... src/commands/impl/NickCommand.o"
	@echo "... src/commands/impl/NickCommand.i"
	@echo "... src/commands/impl/NickCommand.s"
	@echo "... src/commands/impl/NoticeCommand.o"
	@echo "... src/commands/impl/NoticeCommand.i"
	@echo "... src/commands/impl/NoticeCommand.s"
	@echo "... src/commands/impl/PartCommand.o"
	@echo "... src/commands/impl/PartCommand.i"
	@echo "... src/commands/impl/PartCommand.s"
	@echo "... src/commands/impl/PassCommand.o"
	@echo "... src/commands/impl/PassCommand.i"
	@echo "... src/commands/impl/PassCommand.s"
	@echo "... src/commands/impl/PingCommand.o"
	@echo "... src/commands/impl/PingCommand.i"
	@echo "... src/commands/impl/PingCommand.s"
	@echo "... src/commands/impl/PongCommand.o"
	@echo "... src/commands/impl/PongCommand.i"
	@echo "... src/commands/impl/PongCommand.s"
	@echo "... src/commands/impl/PrivMsgCommand.o"
	@echo "... src/commands/impl/PrivMsgCommand.i"
	@echo "... src/commands/impl/PrivMsgCommand.s"
	@echo "... src/commands/impl/QuitCommand.o"
	@echo "... src/commands/impl/QuitCommand.i"
	@echo "... src/commands/impl/QuitCommand.s"
	@echo "... src/commands/impl/TopicCommand.o"
	@echo "... src/commands/impl/TopicCommand.i"
	@echo "... src/commands/impl/TopicCommand.s"
	@echo "... src/commands/impl/UserCommand.o"
	@echo "... src/commands/impl/UserCommand.i"
	@echo "... src/commands/impl/UserCommand.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network/Channel.o"
	@echo "... src/network/Channel.i"
	@echo "... src/network/Channel.s"
	@echo "... src/network/Client.o"
	@echo "... src/network/Client.i"
	@echo "... src/network/Client.s"
	@echo "... src/network/Server.o"
	@echo "... src/network/Server.i"
	@echo "... src/network/Server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

